### ISSUE TITLE
`encode' / "\xE3" from ASCII-8BIT to UTF-8

### ISSUE THREAD

**Issue by yoheimuta** [sowawa/fluent-plugin-slack#37]
In our production environment, to_json errors have occurred after updating td-agent v2.3.5.

```
2017-05-16 17:20:23 +0900 [error]: plugin/out_slack.rb:231:rescue in write: out_slack: error="\"\\xE3\" from ASCII-8BIT to UTF-8" error_class="Encoding::UndefinedConversionError"
```

This error is when fluent-plugin-slack to_json the output of fluent-plugin-rds-slowlog (v0.7.0).
Specifically, in-rds-slowlog outputs ASCII-8BIT encoded character string, but out_slack's to_json expects UTF-8 encoded character string, so it is an error.

- ref. https://github.com/kenjiskywalker/fluent-plugin-rds-slowlog/pull/17

Since the same thing can happen besides in-rds-slowlog, I want to use Yajl instead of JSON, because to_json method raise error when receive multibyte text.

- ref. https://github.com/awslabs/aws-fluent-plugin-kinesis/pull/22

How about that? If so, I will make a PR.

**Comment by sonots** [comment]
About yajl:

JSON string is defined as a sequence of zero or more Unicode characters in RFC4627.
http://www.ietf.org/rfc/rfc4627

So, it is natural to get errors if we try to make a json from some kinds of binaries.
I am not sure how yajl treat this situation. Does it specify its own special specification? How does it behave?

I rather think, if yajl does not raise an error for non unicode strings, it is a **bug** of yajl.

**Comment by sonots** [comment]
About error:

We may be able to take an approach as:

```
begin
   record.to_json
rescue Encoding::UndefinedConversionError => e
   record.each {|k, v| record[k] = v.scrub('?') if v.respond_to?(:scrub) }
   # we should scrub recursively actually
   retry # we should retry only once actually
end
```

although this replaces non unicord chacters with ? focedly

**Comment by yoheimuta** [comment]
> About yajl:

Surely I think it is true. By the way, when I changed it as follows, I could encode a hash containing ASCII-8BIT encoded string without raising any error with yajl.

```
diff --git a/lib/fluent/plugin/slack_client.rb b/lib/fluent/plugin/slack_client.rb
index df9063e..02baba2 100644
--- a/lib/fluent/plugin/slack_client.rb
+++ b/lib/fluent/plugin/slack_client.rb
@@ -2,6 +2,7 @@ require 'uri'
 require 'net/http'
 require 'net/https'
 require 'logger'
+require 'yajl'
 require_relative 'slack_client/error'

 module Fluent
@@ -115,7 +116,8 @@ module Fluent

       def encode_body(params = {})
         # https://api.slack.com/docs/formatting
-        params.to_json.gsub(/&/, '&amp;').gsub(/</, '&lt;').gsub(/>/, '&gt;')
+        params = Yajl.dump(params)
+        params.gsub(/&/, '&amp;').gsub(/</, '&lt;').gsub(/>/, '&gt;')
       end

       def response_check(res, params)
```

**Comment by yoheimuta** [comment]
> About error:
>> although this replaces non unicord chacters with ? focedly

Personally, this approach is more helpful than not being able to send at all with errors.

**Comment by sonots** [comment]
Agree. I may create a patch, but PR is always welcome!

**Comment by yoheimuta** [comment]
Thanks!

**Comment by sonots** [comment]
fixed via https://github.com/sowawa/fluent-plugin-slack/pull/38
