### ISSUE TITLE
can not find slack plugin

### ISSUE THREAD

**Issue by xiaomage008** [sowawa/fluent-plugin-slack#42]
I have installed the slack plugin. When checked with "gem list", it shows "fluent-plugin-slack (0.6.7)". And when i started fluentd, it shows "config error file="/etc/td-agent/td-agent.conf" error_class=Fluent::ConfigError error="Unknown output plugin 'slack'. Run 'gem search -rd fluent-plugin' to find plugins". It seems the plugin does not install, why?

**Comment by sonots** [comment]
It looks not an issue of this plugin, and your environment dependent problem.
please ask to td-agent or somewhere else.
